export const Images = {
  avatar: require("../assets/images/avatar.png"),
    avatar1: require("../assets/images/avatar1.jpg"),
    avatar2: require("../assets/images/avatar2.jpg"),
    avatar3: require("../assets/images/avatar3.jpg"),
    avatar4: require("../assets/images/avatar4.jpg"),
    avatar5: require("../assets/images/avatar5.jpg"),
    empty: require("../assets/images/empty.jpg"),
    gem: require("../assets/images/gem.png"),
    logo: require("../assets/images/logo.png"),
    icon: require("../assets/images/icon.png"),
    onboard1: require("../assets/images/onboard1.jpg"),
    onboard2: require("../assets/images/onboard2.jpg"),
    pic1: require("../assets/images/pic1.jpg"),
    shield: require("../assets/images/shield.jpg"),
    slide1: require("../assets/images/slide1.jpg"),
    slide2: require("../assets/images/slide2.jpg"),
    slide3: require("../assets/images/slide3.jpg"),
    splash: require("../assets/images/splash.png"),
  upgrade: require("../assets/images/upgrade.jpg"),
    banner:require("../assets/images/banner.jpg"),
};